name: Build aws-opentelemetry wheels
description: |
  This action assumes that the repo was checked out and Python is set up. Builds the
  aws-opentelemetry-application-signals, aws-opentelemetry-serviceevents, and
  aws-opentelemetry-distro wheels into ./dist.

runs:
  using: "composite"
  steps:
    - name: Install Dependencies and Build Wheels
      shell: bash
      run: |
        pip install --upgrade pip setuptools wheel packaging build
        rm -rf ./dist/*
        for pkg in aws-opentelemetry-application-signals aws-opentelemetry-serviceevents aws-opentelemetry-distro; do
          (cd "./$pkg" && python -m build --outdir ../dist)
        done
