version: '3'
services:
  db:
    image: mysql:8.0
    container_name: vehicle_inventory_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-pqwerty", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
    expose:
      - 3306

  vehicle-inventory-backend:
    image: pythonsampleapp/vehicle-inventory-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle_inventory_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8001"
    restart: always
    volumes:
      - .:/vehicle-inventory-app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
       db:
          condition: service_healthy
volumes:
  data: