# Generated by Django 5.0 on 2024-01-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("image_name", models.TextField(max_length=255)),
            ],
        ),
    ]
