# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# pylint: skip-file
# Generated by Django 5.0 on 2024-02-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainService", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclePurchaseHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_id", models.IntegerField()),
                ("purchase_date", models.DateField(auto_now_add=True)),
                ("purchase_price", models.IntegerField()),
            ],
        ),
    ]
