# Generated by Django 5.0 on 2024-01-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
