# Generated by Django 5.0 on 2024-02-27 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainService", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclePurchaseHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("purchase_date", models.DateField(auto_now_add=True)),
                ("purchase_price", models.IntegerField()),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="MainService.vehicle")),
            ],
        ),
    ]
