name: Build and Push aws-opentelemetry-distro
description: |
  This action assumes that the repo was checked out. Builds and pushes/loads wheel and image files. Also performs scan
  of the resultant image.

inputs:
  aws-region:
    required: false
    description: "AWS Region, required only if push_image is true"
  image_uri_with_tag:
    required: true
    description: "Image URI with Tag"
  image_registry:
    required: false
    description: "Image Registry, required only if push_image is true"
  snapshot-ecr-role:
    required: false
    description: "IAM Role used for pushing to snapshot ecr, required only if push_image is true"
  push_image:
    required: true
    description: "Whether push image to ECR"
  load_image:
    required: true
    description: "Whether load the image for the following use, only load in PR build"
  python_version:
    required: true
    description: "The python version used in actions"
  package_name:
    required: true
    description: "The package name"
  os:
    required: true
    description: "The os"


runs:
  using: "composite"
  steps:
    - name: Action verification
      if: ${{ (inputs.load_image == false || inputs.load_image == 'false') && (inputs.push_image == false || inputs.push_image == 'false') }}
      shell: bash
      run: |
        echo "At least one of push_image or load_image must be true" 
        exit 1

    - name: Set up
      uses: ./.github/actions/set_up
      with:
        python_version: ${{ inputs.python_version }}
        package_name: ${{ inputs.package_name }}
        os: ${{ inputs.os }}
        run_unit_tests: true


    - name: Install Dependencies and Build Wheel
      id: staging_wheel_build
      shell: bash
      run: |
        pip install --upgrade pip setuptools wheel packaging build
        rm -rf ./dist/*
        cd ./aws-opentelemetry-distro
        python -m build --outdir ../dist
