# Meant to be run from aws-otel-python-instrumentation
# Assumes existence of dist/aws_opentelemetry_distro-<pkg_version>-py3-none-any.whl.
# Assumes filename of aws_opentelemetry_distro-<pkg_version>-py3-none-any.whl is passed in as "DISTRO" arg.
FROM python:3.10
WORKDIR /app
COPY ./dist/$DISTRO /app
COPY ./sample-applications/simple-flask-service /app

RUN rm -rf venv
ENV PIP_ROOT_USER_ACTION=ignore
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

EXPOSE 8080 8081

ARG DISTRO
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install psutil py-spy && pip install ${DISTRO} --force-reinstall
RUN opentelemetry-bootstrap -a install