# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Use an official Python runtime as a parent image
FROM python:3.10

# Set up args
ARG DISTRO

# Set environment variables
ENV PIP_ROOT_USER_ACTION=ignore
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /vehicle-inventory-app

# Copy the project code and distro file into the container
COPY ./sample-applications/vehicle-dealership-sample-app/VehicleInventoryApp /vehicle-inventory-app/
COPY ./dist/$DISTRO /vehicle-inventory-app/

# Install dependencies and distro
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install psutils && pip install ${DISTRO} \
    --force-reinstall