# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Use an official Python runtime as a parent image
FROM python:3.10

# Set environment variables
ENV PIP_ROOT_USER_ACTION=ignore
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /image-service-app

# Copy the project code into the container
COPY ./sample-applications/vehicle-dealership-sample-app/ImageServiceApp/. /image-service-app/

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt