## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

# This is a reusable workflow for running the E2E test for Application Signals.
# It is meant to be called from another workflow.
# Read more about reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
name: E2E Testing
on:
  workflow_call:
    inputs:
      staging-wheel-name:
        required: true
        type: string
      adot-image-name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ inputs.aws-region }}'
  cancel-in-progress: false


jobs:
  upload-main-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.APPLICATION_SIGNALS_E2E_TEST_ACCOUNT_ID }}:role/${{ secrets.APPLICATION_SIGNALS_E2E_TEST_ROLE_NAME }}
          aws-region: us-east-1

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.staging-wheel-name }}

      - name: Upload main-build adot.whl to s3
        run: aws s3 cp ${{ inputs.staging-wheel-name }} s3://adot-main-build-staging-jar/${{ inputs.staging-wheel-name }}

  #
  # PACKAGED DISTRIBUTION LANGUAGE VERSION COVERAGE
  # DEFAULT SETTING: {Python Version}, EC2, AMD64, AL2
  #

  default-v8-amd64:
    needs: [ upload-main-build ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-default-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      python-version: '3.8'
      cpu-architecture: 'x86_64'
      staging-wheel-name: ${{ inputs.staging-wheel-name }}

  default-v11-amd64:
    needs: [ upload-main-build ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-default-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      python-version: '3.9'
      cpu-architecture: 'x86_64'
      staging-wheel-name: ${{ inputs.staging-wheel-name }}

  default-v17-amd64:
    needs: [ upload-main-build ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-default-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      python-version: '3.10'
      cpu-architecture: 'x86_64'
      staging-wheel-name: ${{ inputs.staging-wheel-name }}

  default-v21-amd64:
    needs: [ upload-main-build ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-default-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      python-version: '3.11'
      cpu-architecture: 'x86_64'
      staging-wheel-name: ${{ inputs.staging-wheel-name }}

  default-v22-amd64:
    needs: [ upload-main-build ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-default-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      python-version: '3.12'
      cpu-architecture: 'x86_64'
      staging-wheel-name: ${{ inputs.staging-wheel-name }}

  #
  # DOCKER DISTRIBUTION LANGUAGE VERSION COVERAGE
  # DEFAULT SETTING: {Python Version}, EKS, AMD64, AL2
  #

  eks-v3-8-amd64:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-eks-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-python-adot-test'
      adot-image-name: ${{ inputs.adot-image-name }}
      caller-workflow-name: 'main-build'
      python-version: '3.8'

  eks-v3-9-amd64:
    if: ${{ always() }}
    needs: eks-v3-8-amd64
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-eks-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-python-adot-test'
      adot-image-name: ${{ inputs.adot-image-name }}
      caller-workflow-name: 'main-build'
      python-version: '3.9'

  eks-v3-10-amd64:
    if: ${{ always() }}
    needs: eks-v3-9-amd64
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-eks-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-python-adot-test'
      adot-image-name: ${{ inputs.adot-image-name }}
      caller-workflow-name: 'main-build'
      python-version: '3.10'

  eks-v3-11-amd64:
    if: ${{ always() }}
    needs: eks-v3-10-amd64
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-eks-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-python-adot-test'
      adot-image-name: ${{ inputs.adot-image-name }}
      caller-workflow-name: 'main-build'
      python-version: '3.11'

  eks-v3-12-amd64:
    if: ${{ always() }}
    needs: eks-v3-11-amd64
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-eks-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-python-adot-test'
      adot-image-name: ${{ inputs.adot-image-name }}
      caller-workflow-name: 'main-build'
      python-version: '3.12'

  #
  # PACKAGED DISTRIBUTION PLATFORM COVERAGE
  # DEFAULT SETTING: Python 3.9, {Platform}, AMD64, AL2
  #

  asg-v11-amd64:
    needs: [ upload-main-build ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-asg-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      python-version: '3.9'
      staging-wheel-name: ${{ inputs.staging-wheel-name }}

  #
  # DOCKER DISTRIBUTION PLATFORM COVERAGE
  # DEFAULT SETTING: Python 3.10, {Platform}, AMD64, AL2
  #

  k8s-v11-amd64:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-k8s-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      adot-image-name: ${{ inputs.adot-image-name }}
      caller-workflow-name: 'main-build'
      python-version: '3.10'


  ecs-v11-amd64:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ecs-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      adot-image-name: ${{ inputs.adot-image-name }}
      caller-workflow-name: 'main-build'
      python-version: '3.10'

  #
  # CPU ARCHITECTURE COVERAGE
  # DEFAULT SETTING: Python 3.9, EC2, {CPU Architecture}, AL2
  #

  default-v11-arm64:
    needs: [ upload-main-build ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-default-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      python-version: '3.9'
      cpu-architecture: 'arm64'
      staging-wheel-name: ${{ inputs.staging-wheel-name }}

  #
  # Lambda layer integration tests
  lambda:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-lambda-test.yml@main
    secrets: inherit
    with:
      aws-region: us-east-1
      python-version: '3.12'
      caller-workflow-name: 'main-build'
