# SPDX-License-Identifier: Apache-2.0
name: PR Changelog Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review
    branches:
      - main
      - "release/v*"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #5.0.0
        with:
          fetch-depth: 0

      - name: Check CHANGELOG
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          if [[ "$PR_AUTHOR" == "aws-application-signals-bot" || "$PR_AUTHOR" == "dependabot[bot]" ]]; then
            echo "Skipping check: PR from $PR_AUTHOR"
            exit 0
          fi

          if jq -e 'any(.[]; . == "skip changelog")' <<< "$PR_LABELS" > /dev/null; then
            echo "Skipping check: skip changelog label found"
            exit 0
          fi

          git fetch origin "$BASE_REF"
          if git diff --name-only "origin/$BASE_REF"..HEAD | grep -q "CHANGELOG.md"; then
            echo "CHANGELOG.md entry found - check passed"
            exit 0
          fi

          echo "It looks like you didn't add an entry to CHANGELOG.md. If this change affects the SDK behavior, please update CHANGELOG.md and link this PR in your entry. If this PR does not need a CHANGELOG entry, you can add the 'Skip Changelog' label to this PR."
          exit 1
