name: Nightly Upstream Snapshot Build

on:
  schedule:
    - cron: "21 3 * * *"
  workflow_dispatch:

jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
      otel_python_version: ${{ steps.get_versions.outputs.otel_python_version }}
      otel_contrib_version: ${{ steps.get_versions.outputs.otel_contrib_version }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure git and create branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        BRANCH_NAME="nightly-deps-$(date +%Y%m%d)"
        git checkout -b "$BRANCH_NAME"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install toml requests
    
    - name: Get latest upstream versions
      id: get_versions
      run: python scripts/get_upstream_versions.py
    
    - name: Update dependencies
      env:
        OTEL_PYTHON_VERSION: ${{ steps.get_versions.outputs.otel_python_version }}
        OTEL_CONTRIB_VERSION: ${{ steps.get_versions.outputs.otel_contrib_version }}
      run: python scripts/update_dependencies.py
    
    - name: Check for changes and create PR
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "No dependency updates needed"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Dependencies were updated"
          echo "has_changes=true" >> $GITHUB_OUTPUT
          
          # Create PR immediately
          git add aws-opentelemetry-distro/pyproject.toml
          git commit -m "chore: update OpenTelemetry dependencies to ${{ steps.get_versions.outputs.otel_python_version }}/${{ steps.get_versions.outputs.otel_contrib_version }}"
          git push origin "$BRANCH_NAME"
          
          gh pr create \
            --title "Nightly dependency update: OpenTelemetry ${{ steps.get_versions.outputs.otel_python_version }}/${{ steps.get_versions.outputs.otel_contrib_version }}" \
            --body "Automated update of OpenTelemetry dependencies.

          **Updated versions:**
          - OpenTelemetry Python: ${{ steps.get_versions.outputs.otel_python_version }}
          - OpenTelemetry Contrib: ${{ steps.get_versions.outputs.otel_contrib_version }}

          **Status:** Tests are running in the nightly workflow. Check the workflow results for compatibility status.

          This PR will trigger additional validation via pr-build workflow including multi-version testing and linting." \
            --base main \
            --head "$BRANCH_NAME" \
            --label "dependencies"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest
    needs: update-and-create-pr
    if: needs.update-and-create-pr.outputs.has_changes == 'true'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: nightly-deps-$(date +%Y%m%d)
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build pytest toml requests
    
    - name: Build and test
      uses: ./.github/actions/artifacts_build
      with:
        image_uri_with_tag: adot-python-nightly:snapshot
        push_image: false
        load_image: true
        python_version: "3.11"
        package_name: aws-opentelemetry-distro
        os: ubuntu-latest
    
    - name: Build and Test Lambda Layer
      uses: ./.github/actions/lambda_artifacts_build
      with:
        python_version: "3.12"
        layer_directory: lambda-layer
        staging_s3_bucket: "nightly-test-bucket"
        os: ubuntu-latest
    
    - name: Run contract tests
      run: |
        bash scripts/set-up-contract-tests.sh
        pip install pytest
        pytest contract-tests/tests
