name: Test Main Workflow
on:
  workflow_dispatch:
    inputs:
      should_fail:
        description: 'Should this workflow fail?'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Running for 30 seconds..."
          sleep 30
          if [ "${{ github.event.inputs.should_fail }}" = "true" ]; then
            echo "Failing as requested"
            exit 1
          else
            echo "Succeeding as requested"
          fi
